app/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('cadastro', cadastro, name="cadastro"),
    path('login', login_cliente, name='login'),
    path('login_adm', login_adm, name='login_adm'),
    path('logout', logout_cliente, name='logout'),
    path('logout_adm', logout_adm, name='logout_adm'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from app.views import *

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', splashScreen, name='splashScreen'),
    path('adm/', homeAdm, name='homeAdm'),
    path('clientes/', adm_Cliente, name='clientes_Adm'),
    path('cliente/', homeCliente, name='homeCliente'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('view/<int:pk>/<str:username>/', view, name='view'),
    path('resultado/<int:pk>/', resultadoFinal, name='resultadoFinal'),
    path('update/<int:pk>/', update, name='update'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('view/<int:pk>/', view, name='view'),
    path('solicitacoes/', solicitacoes, name='solicitacoes'),
    path('solicitacoesClientes/', solicitacoesAdm, name='solicitacoesAdm'),
    path('documentos/', docs, name='docs'),
]

app/models.py
from django.db import models
from datetime import date
from django.db.models.fields import DateTimeField, DecimalField, IntegerField
from django.db.models.fields import DateTimeField, IntegerField

# Create your models here.
class Cliente(models.Model):
    nome = models.CharField(max_length=20)
    sobrenome = models.CharField(max_length=20)
    cnpj = models.CharField(max_length=14)
    estado_Civil = models.CharField(max_length=25)
    contato_SMS = models.CharField(max_length=11)
    whatsapp = models.CharField(max_length=11)
    senha_Cliente = models.CharField(max_length=15)
    nome_De_Usuario = models.CharField(max_length=40)
    email_Cliente = models.EmailField()

class Emprestimo(models.Model):
    nomeCliente = models.CharField(max_length=40)
    valor = models.IntegerField()
    data_Solicitacao = models.DateField()
    qtde_Parcelas = models.IntegerField()
    valor_unitario = models.IntegerField(null=True)
    situacao = models.CharField(max_length=40)

class Pagamento(models.Model):
    limite = models.DecimalField(default=0.00, max_digits=60, decimal_places=2)
    form_Pag = models.CharField(max_length=20)

class Resultado(models.Model):
    id_Cliente = models.ForeignKey(Cliente, null=True, on_delete=models.CASCADE, default=None)
    nomeCliente = models.CharField(max_length=40)
    pagamento_em_dia = models.IntegerField()
    inadimplencia = models.IntegerField()
    score_Cliente = models.IntegerField()

class Cliente_Pagamento(models.Model):
    id_Pag = models.OneToOneField(Pagamento, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Pagamento
    id_Cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Cliente
    data_Pagamento = models.DateField()

class Localidade_Estado(models.Model):
    nome_Estado = models.CharField(max_length=20)

class Tipo_Logradouro(models.Model):
    tipo_Logradouro = models.CharField(max_length=15)
    id_Estado = models.ForeignKey(Localidade_Estado, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Localidade_Estado

class Endereco_Empresa_Cliente(models.Model):
    nome_Rua_Comercial = models.CharField(max_length=40)
    num_Rua_Comercial = models.IntegerField()
    id_Tipo_Logradouro = models.ForeignKey(Tipo_Logradouro, on_delete=models.CASCADE, default=None) # Chave estrangeira da classe Tipo_Logradouro

class Formulario(models.Model):
    id_Cliente = models.OneToOneField(Cliente, null=True, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Cliente
    nomeCliente = models.CharField(max_length=40)
    id_Endereco_Empresa = models.ForeignKey(Endereco_Empresa_Cliente, null=True, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Endereco_Empresa_Cliente
    balancos = models.CharField(max_length=200)
    faturamento_Anual = models.DecimalField(default=0.00, max_digits=60, decimal_places=2)
    doc_Contrato_Social = models.CharField(max_length=120)
    renda_Bruta_Anual = models.DecimalField(default=0.00, max_digits=60, decimal_places=2)
    indice_Liquidez = models.DecimalField(default=0.00, max_digits=60, decimal_places=2)
    doc_Indice_Dividas = models.CharField(max_length=60)
    rentabilidade_Investimentos = models.DecimalField(default=0.00, max_digits=60, decimal_places=2)
    holerites_Doc = models.CharField(max_length=60)
    doc_Declaracao_IR = models.CharField(max_length=60)
    receita_Operacional = models.CharField(max_length=200)
    doc_Valores_Contabeis = models.CharField(max_length=40)
    envioDocs = models.IntegerField()

class Tipo_Telefone(models.Model):
    tipo_Telefone = models.CharField(max_length=15)

class Telefones_Cliente(models.Model):
    id_Tipo_Telefone = models.ForeignKey(Tipo_Telefone, on_delete=models.CASCADE, default=None) # Chave estrangeira da classe Tipo_Telefone
    id_Cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, default=None)# chave estrangeira da classe Cliente
    numero_Telefone = models.CharField(max_length=11)

class Endereco_Cliente(models.Model):
    id_Cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Cliente
    id_Tipo_Logradouro = models.ForeignKey(Tipo_Logradouro, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Tipo_Logradouro
    nome_Rua = models.CharField(max_length=40)
    num_Rua = models.IntegerField()
    complemento = models.IntegerField()
    cep = models.CharField(max_length=8)

class Agencia(models.Model):
    nome_Agencia = models.CharField(max_length=40)
    estado = models.CharField(max_length=20)
    nome_Dono = models.CharField(max_length=40)
    logradouro = models.CharField(max_length=20)
    complemento = models.CharField(max_length=20)
    nome_Rua = models.CharField(max_length=40)
    numero_Rua = models.IntegerField()
    cep = models.CharField(max_length=8)
    doc_Contrato_Social = models.CharField(max_length=200)
    doc_Historia_Empresa = models.CharField(max_length=200)
    qtde_Func = models.IntegerField()
    qtde_Dep = models.IntegerField()
    qtde_Anunciantes = models.IntegerField()
    total_clientes = models.IntegerField()
    inadimplentes = models.IntegerField()
    pag_em_dia = models.IntegerField()
    pag_atrasados = models.IntegerField()

class Administrador(models.Model):
    id_Agencia = models.ForeignKey(Agencia, null=True, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Agencia
    nome_Adm = models.CharField(max_length=20)
    senha_Adm = models.CharField(max_length=15)
    id_Cliente = models.ForeignKey(Cliente, null=True, on_delete=models.CASCADE, default=None) # Chave estrangeira da classe Cliente

class Sistema_Rn(models.Model):
    id_Cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Cliente
    id_Resultado = models.ForeignKey(Resultado, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Resultado
    id_Agencia = models.OneToOneField(Agencia, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Agencia 


class Localidade_Cidade(models.Model):
    id_Estado = models.ForeignKey(Localidade_Estado, on_delete=models.CASCADE, default=None) # chave estrangeira da classe Localidade_Estado
    nome_Cidade = models.CharField(max_length=20)

class Localidade_Bairro(models.Model):
    id_Localidade_Cidade = models.OneToOneField(Localidade_Cidade, on_delete=models.CASCADE, default=None) # chave estrangiera da classe Localidade_Cidade
    nome_Bairro = models.CharField(max_length=20)

app/templates/clienteSide/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cliente | Cadastro</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="../../static/style.css">
</head>
<body>
  {% load crispy_forms_tags %}
  <div class="content col-8 m-auto pt-4 pb-2 text-center">
    <h1 class="title">Cadastro</h1>
    <div id="result"></div>
    <form name="form" id="form" action="{% if db %}/update/{{db.id}}/{% else %} /create/{% endif %}" method="POST">
      <div class="form">
        {% csrf_token %}
        <!-- <div id="div_id_id_Cliente" class="form-group">
          <label for="id_id_Cliente" class=" requiredField"></label>
          <div class="">
            <select name="id_Cliente" class="select form-control" required="" id="id_id_Cliente">
              <option value="" selected>Selecione um cliente</option>
              {% for dbs in db  %}
              <option value="">{{dbs.nome}}</option>
              {% endfor %}
            </select>
          </div>
        </div> -->
        <div id="div_id_senha_Cliente" class="form-group">
          <div class="">
            <div class="form-floating mt-3">
              <input type="password" maxlength="15" class="textinput textInput form-control" required="" id="id_senha_Cliente" placeholder="Password" name="senha_Cliente">
              <label for="id_senha_Cliente" class=" requiredField">Password</label>
            </div>
          </div>
        </div>
        <div id="div_id_nome_De_Usuario" class="form-group">
          <div class="">
            <div class="form-floating mt-3">
              <input type="text" name="nome_De_Usuario" maxlength="40" class="textinput textInput form-control" required="" id="id_nome_De_Usuario" placeholder="Username">
              <label for="id_nome_De_Usuario" class=" requiredField">Username</label>
            </div>
          </div>
        </div>
        <div id="div_id_email_Cliente" class="form-group">
          <div class="">
            <div class="form-floating mt-3">
              <input type="email" name="email_Cliente" maxlength="254" class="emailinput form-control" required="" id="id_email_Cliente" placeholder="E-mail">
              <label for="id_email_Cliente" class=" requiredField">E-mail</label>
            </div>
          </div>
        </div>
        <input onclick="" type="submit" class="btn btn-success mt-4" value="Cadastrar">
      </div>
    </form>
  </div>
  <style>
    .requiredField {
      text-align: left;
      display: flex;
      padding: 10px;
      font-weight: bolder;
      font-size: larger;
    }
  </style>  
  <script>
    function prosseguir() {
      alert('Ao cadastrar você será redirecionado a página para realizar a ficha cadastral.')
      window.location.href = '/form_User'
    }
  </script>  
  {% load static %}
  </script src="{% static 'javascript.js' %}">
  </body>
</html>

      

app/templates/clienteSide/documentos.html
{% extends 'clienteSide/clienteHomeScreen.html' %}
{% block title %}Cliente | Documentação{% endblock %}
{% block content %}
<div class="asb">
  <form method="GET" class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Buscar documento..." placeholder="Search" name="search" id="search" aria-label="Search">
      <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
      {% if db %}
      <ul class="list-group list-group-flush">
        {% for dbs in db %}
        <h4 style="margin-bottom: 0%; margin-top: 10px;">DOCUMENTOS</h4>
          <hr style="padding: 2px;">
        {% if search == 'Balanços' %}
        <li class="list-group-item">{{dbs.balancos}}</li>
        {% elif search == 'Faturamento' %}
        <li class="list-group-item">{{dbs.faturamento_Anual}}</li>
        {% elif search == 'Contrato social' %}
        <li class="list-group-item">{{dbs.doc_Contrato_Social}}</li>
        {% elif search == 'Renda Bruta' %}
        <li class="list-group-item">{{dbs.renda_Bruta_Anual}}</li>
        {% elif search == 'Indice liquidez' %}
        <li class="list-group-item">{{dbs.indice_Liquidez}}</li>
        {% elif search == 'Indice de dívidas' %}
        <li class="list-group-item">{{dbs.doc_Indice_Dividas}}</li>
        {% elif search == 'Rentabilidade investimentos' %}
        <li class="list-group-item">{{dbs.rentabilidade_Investimentos}}</li>
        {% elif search == 'Holerites' %}
        <li class="list-group-item">{{dbs.holerites_Doc}}</li>
        {% elif search == 'Declaração IR' %}
        <li class="list-group-item">{{dbs.doc_Declaracao_IR}}</li>
        {% elif search == 'Receita operacional' %}
        <li class="list-group-item">{{dbs.receita_Operacional}}</li>
        {% elif search == 'Valores contabeis' %}
        <li class="list-group-item">{{dbs.doc_Valores_Contabeis}}</li> 
        {% else %}
          <li class="list-group-item">{{dbs.balancos}}</li>
          <li class="list-group-item">{{dbs.faturamento_Anual}}</li>
          <li class="list-group-item">{{dbs.doc_Contrato_Social}}</li>
          <li class="list-group-item">{{dbs.renda_Bruta_Anual}}</li>
          <li class="list-group-item">{{dbs.indice_Liquidez}}</li>
          <li class="list-group-item">{{dbs.doc_Indice_Dividas}}</li>
          <li class="list-group-item">{{dbs.rentabilidade_Investimentos}}</li>
          <li class="list-group-item">{{dbs.holerites_Doc}}</li>
          <li class="list-group-item">{{dbs.doc_Declaracao_IR}}</li>
          <li class="list-group-item">{{dbs.receita_Operacional}}</li>
          <li class="list-group-item">{{dbs.doc_Valores_Contabeis}}</li>
        </ul>
        {% endif %}
        {% endfor %} 
      </ul>
      {% else %}
      <p style="margin-top: 10%;">
        Nenhum dado encontrado...</br>Parece que você ainda não preencheu o formulário.
      </p>
      <input style="width: 100%; font-weight: 400; margin-top: 0%;" class="btn btn-outline-dark" type="button" onclick="toggleMenu()" value="Preencher Formulário">
      {% endif %}
    </div>
    <p style="display: none;" class="requestUser">{{request.user}}</p>
    <div class="div_content">
      <div onclick="toggleMenu();" class="toggle4"></div>
  <div class="row">
    <form style="z-index: 1000;" id="forms" method="post" action="">
      {% csrf_token %}
      <label for="exampleFormControlInput1" class="form-label">Balanços</label>
      <input onmouseover="c()" type="text" name="balancos" placeholder="Valor dos balanços" maxlength="200" required="" id="id_balancos">
      <label for="exampleFormControlInput1" class="form-label">Faturamento Anual</label>
      <input type="number" placeholder="Faturamento anual" name="faturamento_Anual" step="0.01" required="" id="id_faturamento_Anual">
      <label for="exampleFormControlInput1" class="form-label">Contrato Social</label>
      <input type="text" placeholder="Contrato Social" name="doc_Contrato_Social" maxlength="120" required="" id="id_doc_Contrato_Social">
      <label for="exampleFormControlInput1" class="form-label">Renda Anual Bruta</label>
      <input type="number" placeholder="Renda Bruta Anual" name="renda_Bruta_Anual"  step="0.01" required="" id="id_renda_Bruta_Anual">
      <label for="exampleFormControlInput1" class="form-label">Indice de Liquidez</label>
      <input type="number" placeholder="Indice Liquidez" name="indice_Liquidez" step="0.01" required="" id="id_indice_Liquidez">
      <label for="exampleFormControlInput1" class="form-label">Indice de Dívidas</label>
      <input type="text" placeholder="Indice de Dívidas" name="doc_Indice_Dividas" maxlength="60" required="" id="id_doc_Indice_Dividas">
      <label for="exampleFormControlInput1" class="form-label">Rentabilidade em Investimentos</label>
      <input type="number" placeholder="Rentabilidade em Investimentos" name="rentabilidade_Investimentos" step="0.01" required="" id="id_rentabilidade_Investimentos">
      <label for="exampleFormControlInput1" class="form-label">Holerites</label>
      <input type="text" placeholder="Holerites" name="holerites_Doc" maxlength="60" required="" id="id_holerites_Doc">
      <label for="exampleFormControlInput1" class="form-label">Declaração de IR</label>
      <input type="text" placeholder="Declaração de Imposto de Renda" name="doc_Declaracao_IR" maxlength="60" required="" id="id_doc_Declaracao_IR">
      <label for="exampleFormControlInput1" class="form-label">Receita Operacional</label>
      <input type="text" placeholder="Receita Operacional" name="receita_Operacional" required="" id="id_receita_Operacional">
      <label for="exampleFormControlInput1" class="form-label">Valores Contabeis</label>
      <input type="text" placeholder="Valores Contabéis" name="doc_Valores_Contabeis" maxlength="40" required="" id="id_doc_Valores_Contabeis">  
      <input style="display: none;" type="text" name="nomeCliente" maxlength="40" required="" class="id_nomeCliente" id="id_nomeCliente">
      <input type="submit" value="Solicitar" style="font-weight: 500;margin: 5px; padding-left: 50px; margin-top: 30px;" class="btn btn-outline-light" value="Solicitar Empréstimo"> 
    </form>
  </div>
</div>
<p style="display: none;" class="size">{{size}}</p>
<div class="div-content">
  <div id="donutchartt" style="width: 400px; margin-left:8%; margin-top: -13%; height: 350px;"></div>
  <div style="z-index: 100; margin-top: 2%; width: 500px;">
    <h3 style="z-index: 100;" >Você já enviou <!-- <p class="size2">100%</p> -->100% da documentação necessaria para a análise de crédito</h3>
    <p style="z-index: 100;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi eum sit laboriosam, reprehenderit quia illum, nam saepe sunt eveniet omnis perspiciatis at magnam voluptatibus explicabo temporibus sed illo ipsam. Nisi?</p>
</div>
</div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var s = document.querySelector('.size').innerHTML
        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Entregue',     s],
        ]);

        var options = {
          pieHole: 0.5,
          pieSliceTextStyle: {
            color: 'black',
          },
          legend: 'none'
        };

        var chart = new google.visualization.PieChart(document.getElementById('donutchartt'));
        chart.draw(data, options);
      }
    </script>

<script>
  (() => {
    var s = document.querySelector('.size').innerHTML
    document.querySelector('.size2').innerHTML = s
  })()
  function c() {
    var user = document.querySelector('.requestUser');
    document.querySelector('.id_nomeCliente').value = user.innerHTML;
  }
  function toggleMenu() {
    const menuToggle = document.querySelector('.toggle4');
    const sss = document.querySelector('.div_content');
    menuToggle.classList.toggle('active');
    sss.classList.toggle('active');
  }
</script>
{% endblock %}

app/templates/clienteSide/fichaCadastral.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cliente | Ficha cadastral</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <link rel="stylesheet" href="../../static/style.css">
</head>
<body style="background-color: #212529; color: white;">
  {% load crispy_forms_tags %}
  <div class="content col-8 m-auto pt-4 pb-2 text-center">
    <a href="/login"><img style="width: 70px; margin-left: -50%; margin-top: -1%; position: absolute;" src="../../static/img/arrow.png" alt=""></a>
    <h1 style="margin-top: 9%;" class="title">Ficha Cadastral</h1>
    <hr style="padding: 1px;">
    <div id="result"></div>
    <form class="formCadastro" method="post">
      {% csrf_token %}
      <input placeholder="Username" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" class="id_username" id="id_username">
      <input placeholder="Password" type="password" class="id_password1" name="password1" autocomplete="new-password" required="" id="id_password1">
      <input placeholder="Confirm password" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
      <input placeholder="Nome" type="text" name="nome" maxlength="20" required="" id="id_nome">
      <input placeholder="Sobrenome" type="text" name="sobrenome" maxlength="20" required="" id="id_sobrenome">
      <input placeholder="CNPJ" type="text" name="cnpj" maxlength="14" required="" id="id_cnpj">
      <input placeholder="Estado Civil" type="text" name="estado_Civil" maxlength="25" required="" id="id_estado_Civil">
      <input placeholder="SMS" type="text" name="contato_SMS" maxlength="11" required="" id="id_contato_SMS">
      <input placeholder="Whatsapp" type="text" name="whatsapp" maxlength="11" required="" id="id_whatsapp">
      <input onmouseover="inserirDados()" placeholder="email" type="email" required="" name="email" maxlength="254" class="id_email" id="id_email">
      <input style="display: none;" type="text" name="senha_Cliente" maxlength="15" class="senha_cliente" id="id_senha_Cliente">
      <input style="display: none;" type="text" name="nome_De_Usuario" maxlength="40" class="nome_de_usuario" id="id_nome_De_Usuario">
      <input style="display: none;" type="email" name="email_Cliente" maxlength="254" class="email_cliente" id="id_email_Cliente">
      <hr>
      <input type="submit" style="font-weight: 500;margin: 5px; width: 100%;" class="btn btn-outline-light" value="Cadastrar"> 
      </form>
  </div>
  <style>
    .formCadastro {
      align-items: center;
      justify-content: center;
      max-width: min-content;
    }
    .form {
      margin: 10px;
    }
  </style>  
  <script>
    function inserirDados() {
      let password = document.querySelector('.id_password1');
      let email = document.querySelector('.id_email');
      let username = document.querySelector('.id_username');
      document.querySelector('.senha_cliente').value = password.value;
      document.querySelector('.nome_de_usuario').value = username.value;
      document.querySelector('.email_cliente').value = email.value;
    }
  </script>
  {% load static %}
  <script src="{% static 'javascript.js' %}"></script>
</body>
</html>
  
 